### ISSUE TITLE
How to start drawing from outside map

### ISSUE THREAD

**Issue by kevin-wolf** [alex3165/react-leaflet-draw#1]
Hello!

I want to start the drawing action on the map from outside. I am trying to figure out what to do but I didn't come up with a solution.

<img width="1440" alt="screen shot 2016-02-25 at 12 36 28 am" src="https://cloud.githubusercontent.com/assets/3157426/13311931/199c721c-db58-11e5-877a-52bc093f8bc6.png">

According to the image, the controls work fine when I click on the map buttons. But I do want to start the drawing action _also_ when clicking the sidebar buttons.

What do you recommend?

**Comment by alex3165** [comment]
Hey,

I added a prop "onMounted" to EditControl component which is called once the component is mounted, i am passing the "leaflet controls" object so you can use it to trigger a draw with the tool you want, for example this should work to trigger draw a circle tool:

```
  _mounted(drawControl) {
    setTimeout(() => {
      drawControl._toolbars["18"]._modes.circle.handler.enable();
    }, 200)
  }
```

You can store the control into a variable and call enable when you want, for more informations please check the following leaft-draw issue : https://github.com/Leaflet/Leaflet.draw/issues/53

**Comment by ryazhang** [comment]
Hi Alex,
Thanks for your solution.
I have one more requirement that I also need 'delete last point' function outside of the map.
How can I do that with this 'drawControl' object?

**Comment by ryazhang** [comment]
Hi Alex,
Thanks for your solution. 
BTW, as I have the button outside to trigger draw function. How can I hide the toolbar?
If I set polygon: false, button outside is not usable too.

**Comment by NV4RE** [comment]
> Hi Alex,
> Thanks for your solution.
> BTW, as I have the button outside to trigger draw function. How can I hide the toolbar?
> If I set polygon: false, button outside is not usable too.

Add this to your style
`.leaflet-draw {
  display: none;
}`

**Comment by afink170** [comment]
Hi @alex3165 ,

I have a followup question about this.  I am doing something similar.  I have a map that I want to draw rectangles on.  But additionally, I want to be able to completely draw the rectangles and delete the rectangles programmatically. So for example, I have a form with number inputs for a bounding box.  When the user types in the bounding box coordinates, I want the rectangle for the bounding box to automatically drawn on the map.  Then the user should be able to use the standard edit/delete functions on the map.  

I have used the onMounted property to enable drawing like so:

```
_onMounted = drawControl => {
		console.log(drawControl);
		drawControl._toolbars.draw._modes.rectangle.handler.enable();
		// this.drawControl = drawControl;
	};
```
```
<EditControl
        ... // other props
        onMounted={this._onMounted}
>
```

This starts the Draw event for the user, but I want to be able to programmatically call the Draw, Edit, and Delete events to control the map.  Is there already a way to do this using the drawControl object?
