### ISSUE TITLE
Error while loading Marker default image

### ISSUE THREAD

**Issue by BaptWaels** [alex3165/react-leaflet-draw#10]
Hi,

I use : 
- "leaflet": "^1.0.1"
- "react-leaflet": "^1.0.0-rc.2"
- "react-leaflet-draw" : "^0.10.1"

I get this error : 
http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/imagesmarker-icon.png Failed to load resource: 404 (Not Found)
http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/imagesmarker-icon.png Failed to load resource: 404 (Not Found)

It took me a while to understand that react-leaflet-draw had as dependencies an older version of react-leaflet with a [bug](https://github.com/PaulLeCam/react-leaflet/pull/229#issuecomment-255752224) which was loading the wrong images.

Any plan of updating the dependencies to newer versions ? (leaflet, leaflet-draw, react-leaflet)

**Comment by alex3165** [comment]
Hey @BaptWaels I am working on updating the dependencies, the delete feature is broken for now, once it is fixed I will merge the PR : https://github.com/alex3165/react-leaflet-draw/pull/12

**Comment by alex3165** [comment]
@BaptWaels, should be fixed now
