### ISSUE TITLE
TypeError in EditControl.js

### ISSUE THREAD

**Issue by perrigow** [alex3165/react-leaflet-draw#103]
https://github.com/alex3165/react-leaflet-draw/blob/4c6de821a49ca40ef89013a8dd07162348d6926b/src/EditControl.js#L57

I am pretty sure this was missed during the migration to react-leaflet v3. Shouldn't this line read const { map } = context; as props.leaflet is undefined.

**Comment by Console2016** [comment]
I had the same problem
