### ISSUE TITLE
EditControl not toggleable

### ISSUE THREAD

**Issue by Eastonboy99** [alex3165/react-leaflet-draw#119]
I'm trying to make the edit controls show when a user clicks a specific button. When the app starts and the state is false, the controls are not shown. When the user clicks the button, the controls are shown. Now when the user clicks that button and the state returns to false, the controls are still shown. Then when the user clicks it again, this time setting the state to true, another set of controls are added. Any ideas?

Here is a sandbox with an example of what happens: https://codesandbox.io/s/sweet-mountain-27ed3?file=/src/edit-control.js:2246-2423

**Comment by gnunesinf** [comment]
I had the same issue, but the solution proposed by @dave-b-armstrong wasn't successful. Besides that, I was able to achieve that comportment calling the remove function that exists in drawRef

Basically, inside the return function on the first useEffect i made this: 

` return () => {
      map.off(leaflet.Draw.Event.CREATED, onDrawCreate);

      for (const key in eventHandlers) {
        if (props[key]) {
          map.off(eventHandlers[key], props[key]);
        }
      }

      drawRef.current.remove();
 };`

Thread that helped me: https://stackoverflow.com/questions/39330092/disable-leaflet-draw-toolbar-when-user-creates-a-shape-and-enable-it-when-the-sh

Hope that helps someone :)

**Comment by brennanwilkes** [comment]
Feel free to submit a PR if you have a good fix! @gnunesinf @dave-b-armstrong
