### ISSUE TITLE
Support React v18

### ISSUE THREAD

**Issue by MLNW** [alex3165/react-leaflet-draw#139]
React v18 has been released about three weeks ago: https://reactjs.org/blog/2022/03/29/react-v18.html

Leaflet and react-leaflet have already upgraded to support this new version. Are there plans to upgrade this package as well?

**Comment by ms77grz** [comment]
up

**Comment by YummyTi** [comment]
please support for React 18, there is error with it

**Comment by brennanwilkes** [comment]
@ms77grz @MLNW  [Version 0.20.0](https://www.npmjs.com/package/react-leaflet-draw/v/0.20.0) patches this issue. Please let me know if there are any bugs or issues with it
