### ISSUE TITLE
TypeError: destroy is not a function

### ISSUE THREAD

**Issue by khatran79** [alex3165/react-leaflet-draw#145]
I am trying to add react-leaflet-draw into the map. 

The code is at https://codesandbox.io/s/elastic-darkness-2ric3h?file=/src/App.js

The map is working fine however got this error TypeError: destroy is not a function

Any idea please?

**Comment by khatran79** [comment]
Working fine when downgrade to react 17.0.2

**Comment by khatran79** [comment]
Working fine when downgrade to react from 18 to 17.0.2

**Comment by brennanwilkes** [comment]
@khatran79  [Version 0.20.0](https://www.npmjs.com/package/react-leaflet-draw/v/0.20.0) patches this issue. Please let me know if there are any bugs or issues with it
