### ISSUE TITLE
Can't Install in React version 18.2.0

### ISSUE THREAD

**Issue by wphatpat** [alex3165/react-leaflet-draw#149]
Hi I tried install package but get this error -> [https://ibb.co/8KGJ9fc](url). How to fix it.

thx.

**Comment by wphatpat** [comment]
solve with --legacy-peer-deps

**Comment by brennanwilkes** [comment]
@wphatpat  [Version 0.20.0](https://www.npmjs.com/package/react-leaflet-draw/v/0.20.0) patches this issue. Please let me know if there are any bugs or issues with it

**Comment by kayes360** [comment]
> [@wphatpat](https://github.com/wphatpat) [Version 0.20.0](https://www.npmjs.com/package/react-leaflet-draw/v/0.20.0) patches this issue. Please let me know if there are any bugs or issues with it

not working with react 19
