### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Kumail09** [alex3165/react-leaflet-draw#158]
ERROR in ./node_modules/react-leaflet-draw/dist/esm/EditControl.js 47:0-56
Module not found: Error: Can't resolve '@react-leaflet/core' in '//node_modules/react-leaflet-draw/dist/esm'

**Comment by thefat32** [comment]
You need to install react-leaflet in your project. This lib depends on it, as stated in "peerDependencies" inside package.json
