### ISSUE TITLE
Should onMounted fire in componentDidMount, instead of before it has mounted?

### ISSUE THREAD

**Issue by markhepburn** [alex3165/react-leaflet-draw#16]
This is arguably a question of semantics, and I've bumped into it attempting something quite ugly that I hope to avoid... nonetheless: when the `onMounted` callback is fired, in the middle of `componentWillMount`, the component has not in fact mounted yet, and thus hasn't been fully initialised if the callback relies on that.

I'm happy to put together a PR if you'd like.

**Comment by alex3165** [comment]
Hey @markhepburn sorry for the late reply, I am not very active on `react-leaflet-draw` you are welcome to open a PR if you want for that 👍 Thanks

**Comment by markhepburn** [comment]
Done :)

**Comment by alex3165** [comment]
Thanks ! 👍

**Comment by alex3165** [comment]
Published with the version `1.4.0`

**Comment by markhepburn** [comment]
Great, thanks for the new version too! 👍
