### ISSUE TITLE
After building a project, gettng error Uncaught ReferenceError: L is not defined at (leaflet.draw.js:8:96)

### ISSUE THREAD

**Issue by neelduttahere** [alex3165/react-leaflet-draw#164]
I don't know how to reproduce as another project of mine doesn't have this issue. Only my project in question has this issue. Everything is working fine on development server. However, after building, I get this error from static files being served. I'm not sure what is exactly causing this, I tried to compare versions of leaflet, react-leaflet-draw, leaflet-draw, to an existing project of mine that has the same dependencies. The existing project works perfectly after built. Only the project that's in question is causing the issue.

`Uncaught ReferenceError: L is not defined
    at 68192 (leaflet.draw.js:8:96)`

I can't figure out why L is turning to be undefined after being built. 

Any help and suggestions would be appreciated

**Comment by neelduttahere** [comment]
Somehow, I solved this issue, turns out it was a compiler bug leaf from a syntax error somewhere in my codebase that was not picked up by compiler.

**Comment by Manikantan-SFS** [comment]
@neelduttahere which compiler you were using ? and what did you do to fix it?
