### ISSUE TITLE
Styling messed up on toolbar

### ISSUE THREAD

**Issue by zeroasterisk** [alex3165/react-leaflet-draw#17]
I get "Draw" text on all my controls in the toolbar, when I add this...

![ss](https://puu.sh/uiETa/0c4a5659f4.png)

- is there extra CSS I should have to add?
- is the "global" `L` in your code importable?  Is there a chance that's our problem, since I don't have `L` in global scope anywhere? _(es6 import modules all the way)_
- I'm trying to set this up in [react-storybook](https://getstorybook.io) which is awesome - but it's been a bit of a pain getting leaflet + css in place...  thoughts?

```
    <Map {...pickMapProps(mapData)}>
      <TileLayer
        url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
      />
      <FeatureGroup>
        <EditControl
          position='topright'
          onEdited={props.onChanged}
          onCreated={props.onChanged}
          onDeleted={props.onChanged}
          draw={{
            rectangle: false
          }}
        />
          <Circle center={[51.51, -0.06]} radius={200} />
      </FeatureGroup>
    </Map>
```

**Comment by zeroasterisk** [comment]
Here's a public example (as far as it goes)
https://zeroasterisk.github.io/react-leaflet-polytools/

**Comment by alex3165** [comment]
Hey, I think they haven't updated their styles so I have pushed an update of the examples, I managed to solve it by using `https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.2/leaflet.draw.css` and I have added this css rule to my css: 
```
  .sr-only {
    display: none;
  }
```

You can check the examples for more details

**Comment by zeroasterisk** [comment]
I have updated things, with your new CSS and their new CSS and the images...  it's better (no wonky texts) and it works for me locally, but not when deployed because I'm currently relying on CSS --> image url --> static path on a storybook, which doesn't seem to translate well to published on github... I may need to figure out how to make the image URLs come through webpack, or change them to be full URLs to a CDN.

Anyway - though - thanks for your help!
https://github.com/zeroasterisk/react-leaflet-polytools/blob/master/src/index.js
