### ISSUE TITLE
Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>

### ISSUE THREAD

**Issue by MistreanuIonutCosmin** [alex3165/react-leaflet-draw#171]
**Issue**
Describe the issue

I am trying to use the latest packages for leaflet, leaflet-draw, react-leaflet and react-leaflet-draw, but I am getting the error "Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>". Everything works fine if I downgrade react-leaflet to version "^3.2.5".

**Expected behavior**

I expect the code to work with the latest packages without any errors.

**Packages used**
"leaflet": "^1.9.3",
"leaflet-draw": "^1.0.4",
"react-leaflet": "^4.2.0",
"react-leaflet-draw": "^0.20.4",
Additional context

I appreciate your awesome repository. I would be grateful if you could suggest a solution for this issue.

**Comment by giovanesantossilva** [comment]
Hello, I would like to suggest trying to use the plugin that I developed in order to solve these and other problems, to learn more at a glance https://github.com/giovanesantosilva/react-leaflet-draft

**Comment by MistreanuIonutCosmin** [comment]
Thank you for your response! I will give it a try! 
Best regards!

**Comment by kolarski** [comment]
I'm not sure what that issue is closed, this is still an issue with the latest version

**Comment by giovanesantossilva** [comment]
Hello, I would like to suggest trying to use the plugin that I developed in order to solve these and other problems, to learn more at a glance https://www.npmjs.com/package/react-leaflet-draft.

**Comment by lyvyu** [comment]
Hello guys, still getting the same issue, is there any chance to be fixed or at least a workaround? 👀

**Comment by giovanesantossilva** [comment]
Hello, of course yes, I will analyze, send me your used packages and more information!

**Comment by giovanesantossilva** [comment]
Hello, this problem was solved in my repository, if you want to take a look there https://github.com/giovanesantosilva/react-leaflet-draft

**Comment by lyvyu** [comment]
@giovanesantossilva thanks for the reply, tried ur repo but I get an error which other guys do to https://github.com/giovanesantossilva/react-leaflet-draft/issues/8

**Comment by giovanesantossilva** [comment]
Of course, I'll check, if I manage to solve it, I'll post it here then!

**Comment by lyvyu** [comment]
> Of course, I'll check, if I manage to solve it, I'll post it here then!

Sure, you can even post on the original issue in ur repo, I’m following both.

Thanks mate!
