### ISSUE TITLE
Updated needed

### ISSUE THREAD

**Issue by Charmatzis** [alex3165/react-leaflet-draw#2]
Hi, 
Nice work @alex3165 !!!!

I believe that in the new version of the react leaflet "0.11.5" your plugin does not work.
The error is "options.featureGroup must be a L.FeatureGroup".

Do you have any time to update your plugin?

THX!

**Comment by alex3165** [comment]
Hey @Charmatzis, I just released a version 0.7.0 of the library that fixe the issue 👍 let me know if it's good for you as well.

Thanks for your issue !

**Comment by Charmatzis** [comment]
Yeap, thx!!!!
