### ISSUE TITLE
Strange behavior editing a polygon

### ISSUE THREAD

**Issue by rabbl** [alex3165/react-leaflet-draw#27]
There is an interesting behavior in leaflet-draw, possibly in combination with the reselect-package.

The expected behavior is that the polygon changes when editing it.

![expected](https://user-images.githubusercontent.com/1965304/29171357-9bc51ed8-7ddc-11e7-9829-a3eae1bc8a71.png)

The real behavior is, that its only changing the outline of it and not the real polygon.

![reality](https://user-images.githubusercontent.com/1965304/29171376-a9608172-7ddc-11e7-92b5-43e0ee67b635.png)

I have debugged a lot and tried to reproduce the error.

I wrote a Component based on the example and added it to my codebase.

https://github.com/inowas/inowas-dss-client/blob/error/leaflet-edit-polygon/src/containers/tools/EditAreaMap.jsx

Adding it here: https://github.com/inowas/inowas-dss-client/blob/error/leaflet-edit-polygon/src/containers/tools/TestLeaflet.js it works as expected.

Adding it to a connected component: https://github.com/inowas/inowas-dss-client/blob/error/leaflet-edit-polygon/src/t03/containers/mainTest.jsx it does not work as expected.

In both cases, the same sample-data is rendered (no state, no props no store-data).

When I'm changing the line https://github.com/inowas/inowas-dss-client/blob/error/leaflet-edit-polygon/src/t03/containers/mainTest.jsx#L36 

from 

`T03T = connect( makeMapStateToProps, mapDispatchToProps )( T03T );`

to 

`T03T = connect( mapStateToProps, mapDispatchToProps )( T03T );`

and it's not depending anymore to the selectors: https://github.com/inowas/inowas-dss-client/blob/error/leaflet-edit-polygon/src/t03/selectors/mapState.js#L40 it works well.

Can you imagine why this happens? How con I debug further this situation?

Best regards
Ralf

**Comment by rabbl** [comment]
I fixed a bug in my reducers and this fixed this error too.
But I cannot explain at the moment why this has happened.
So I'll close this issue.

**Comment by bziraoui** [comment]
Hello,
i have the same issue, when we edit an existing layer, only outline change.
But its work if trigger the event edit when we cancel the first time.

How i can fix this bug ? 

Thanks
