### ISSUE TITLE
Editing a shape

### ISSUE THREAD

**Issue by romansemko** [alex3165/react-leaflet-draw#3]
I have a shape and click on the "edit" button to edit it. When I drag the corner markers of the shape, the whole map is dragged, instead of the shape being edited. What could be the reason for this behavior. Any ideas?

**Comment by romansemko** [comment]
Nevermind. The leaflet draw is incompatible with the newest version of leaflet (1.0RC). The leaflet-master branch of leaflet draw is not 100% ready, yet.

**Comment by alex3165** [comment]
Ok no problem thanks anyway for your commitment 👍  i was about to check this morning.
