### ISSUE TITLE
Map props not found for componentWillMount

### ISSUE THREAD

**Issue by ALTinners** [alex3165/react-leaflet-draw#4]
Hey mate, been having a play with this package in a Meteor app. I'm currently hitting a bug where props.map is undefined when componentWillMount is triggered.

Meteor 1.3 with react-leaflet as a base, so it may be beyond the scope of what you're looking at. I was going to have a play around (see if pushing the map.on(...) functions back to componentDidMount makes a difference) but I can't seem to find a way to rebuild the package....got a gulp/grunt file you use?

Cheers, Tinners

**Comment by TigleyM** [comment]
As of react-leaflet@12.0, I know some breaking changes were implemented where Leaflet instances were moved from props to context. You might have to rollback your version of react-leaflet to 11.7 for react-leaflet-draw to work. 

https://github.com/PaulLeCam/react-leaflet/releases

**Comment by ALTinners** [comment]
Yeah, that looks to be it; cheers @TigleyM 

I'll clone the repo and see if I can get the minimal example to work with react-leaflet@0.12.0, will update here if I get anywhere

**Comment by TigleyM** [comment]
Forked the repo and had to change` EditControl extends MapControl` to `EditControl extends LayersControl` , since layerContainer is no longer accessible via props and LayersControl provides the layerContainer context to its children.

**Comment by alex3165** [comment]
Good job ! thank you for the PR @TigleyM !

**Comment by gpbmike** [comment]
I think this was fixed by #5 and #6. Thanks!
