### ISSUE TITLE
Trouble understanding how to interact with underlying map/objects

### ISSUE THREAD

**Issue by andrewdodd** [alex3165/react-leaflet-draw#45]
I am unsure if this is an issue with this library or just an issue with my understanding. I would really appreciate if anyone can give me some tips.

I am trying to use the `react-leaflet` and `react-leaflet-draw` library, as the draw functionality really looks great (and I prefer to use existing libs where possible).

I have a situation where:
 - I have polygons in my application that I want to draw on a leaflet map
 - I would like to use the leaflet.draw functionality to be able to both:
     - Add new polygons
     - Edit existing polygons

As far as I can understand, the issues I am having are because the `react-leaflet` and `react-leaflet-draw` libraries are really just shims around leaflet.js & leaflet.draw.js, so integrating the 'react' objects with the ones managed by the underlying library is not really working.

The example provided has got me part of the way, but I can't seem to get things to work the way I think I need them to.

My files are as follows:

**Example.js**
```
import React, { Component } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import 'leaflet-draw/dist/leaflet.draw.css';
import {Map,  GeoJSON} from 'react-leaflet';

import EditControlWrapper from './EditControlWrapper';


function getInitPolys(offset) {
  return {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature", "properties": {},
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [[200+offset, 200+offset],
             [100+offset, 0+offset],
             [100+offset, 100+offset]]
          ]
        }
      }
    ]
  }
}

export default class Example extends Component {
  constructor() {
    super();
    this.state = getInitPolys(0);
    this.handleButton = this.handleButton.bind(this);
    this.drawingChanged = this.drawingChanged.bind(this);
  }
  handleButton() {
    // forcibly change the state
    this.setState(getInitPolys(25));
  }
  drawingChanged(e) {
    console.log('Received new GeoJSON', e);
    this.setState(e);
  }

  render() {
    const style={height:"300px",width:"100%",position:"relative"};
    const bounds = [[0,0], [1000,1000]];
    const theGeoJSONs = <GeoJSON data={this.state} />;

    return (
      <div>
        <Map 
          crs={ L.CRS.Simple } 
          bounds={ bounds }
          style={style}
          minZoom={-4}
        >
          <EditControlWrapper onChange={this.drawingChanged}>
            {theGeoJSONs}
          </EditControlWrapper>
      </Map>
      <button onClick={this.handleClick}>Change Input</button>
      </div>
    )
  }
}
```

**EditControlWrapper.js**
```
import React, { Component } from 'react';
import 'leaflet-draw/dist/leaflet.draw.css';
import {FeatureGroup, Circle} from 'react-leaflet';
import { EditControl } from 'react-leaflet-draw';

export default class CustomEditControl extends React.Component {
  render() {
    return (
      <FeatureGroup ref={ (reactFGref) => {this._onFeatureGroupReady(reactFGref);} }>
        <EditControl 
          position='topright'
          onEdited={this._onChange}
          onCreated={this._onChange}
          onDeleted={this._onChange}
        />
        {this.props.children}
      </FeatureGroup>
    );
  }

  _editableFG = null
  _onFeatureGroupReady = (reactFGref) => {
    if (reactFGref) {
      this._editableFG = reactFGref;
   }
  }
  _onChange = () => {
    const { onChange } = this.props;

    if (!onChange || !this._editableFG) {
      return;
    }

    const geojsonData = this._editableFG.leafletElement.toGeoJSON();
    onChange(geojsonData);
  }
}
```

My understanding is that the flow should go something like this:
```
1. Data flow
   Example ---> pushes in polygons through children --> Wrapper --> FeatureGroup

2. Callback flow
   LeafetReactDraw.onEdit/onCreate/onEdit ---> Wrapper --> Example --> setState()
                                      [via callbacks]

3. State change causes React to invalidate components which causes data flow again
```

Because the react-leaflet library is really just a shim around the real leaflet, I'm guessing that we have to remove all of the polygons from the underlying map when one of these components gets updated/unmounted. But where!

Also, this does other weird things like not allowing edits, but it is probably not worth diving into just yet.

Am I on the right path? Or is there an easier way?

Also, if anyone can help with #44 then I can make a codepen for this too.

**Comment by andrewdodd** [comment]
The solution was to not use this library but to write a component very similar.

This was because:
 - I needed access to the `onDrawCreate` event, and to have it not automatically add items to the `FeatureGroup` layer
 - I needed to use `refs` to link my objects with the ones created by Leaflet directly.

**Comment by andrewdodd** [comment]
@gedion I forked and made the changes to both the example code and the actual library classes here https://github.com/andrewdodd/react-leaflet-draw

I also suggest having a look at the commit log.

**Comment by andrewdodd** [comment]
@gedion Did the example help?

**Comment by gedion** [comment]
@andrewdodd - Apologies. Have not had a chance to deepdive. Planning to give it sometime over the weekend.
