### ISSUE TITLE
have plan to add typescript binding?

### ISSUE THREAD

**Issue by dadream** [alex3165/react-leaflet-draw#47]

**Comment by srghma** [comment]
@dadream hi, can you make pr re this one?

**Comment by Nashid95** [comment]
@srghma Any plans on adding making a typescript page/Is there a version that supports type script?

**Comment by srghma** [comment]
@Nashid95 

No, there is no such plan/don't know that

But I can accept pr.

**Comment by hoetmaaiers** [comment]
I provided a PR with typescript typings: https://github.com/alex3165/react-leaflet-draw/pull/72
