### ISSUE TITLE
Module not found: Can't resolve 'leaflet-draw' 

### ISSUE THREAD

**Issue by MehdiJarraya** [alex3165/react-leaflet-draw#60]
Hi guys, 
I got this error when I copied the Get Start example.
./node_modules/react-leaflet-draw/dist/esm/EditControl.js
Module not found: Can't resolve 'leaflet-draw' 
I'm using "react-leaflet-draw": "^0.19.0", "leaflet": "^1.4.0", "react-leaflet": "^2.1.4" and "react": "^16.6.3".

**Comment by umntkid** [comment]
try `npm install leaflet-draw`

**Comment by jawadzahoor72** [comment]
> try `npm install leaflet-draw`
and also install core module
`npm i @react-leaflet/core`
