### ISSUE TITLE
Crash on startup: Object(...) is not a function 

### ISSUE THREAD

**Issue by JediahDizon** [alex3165/react-leaflet-draw#71]
This library crashes when importing the `EditControl` when using React Leaflet 2.0.0^ because the v2 uses React 16's context so it deprecated the `withLeaflet()` decorator.

**Comment by JediahDizon** [comment]
Nevermind. I apparently had wrong sources.

**Comment by WapnerSensefarm** [comment]
@JediahDizon What do you mean by wrong sources? I have this exact problem but can't seem to fix it...

**Comment by JediahDizon** [comment]
> @JediahDizon What do you mean by wrong sources? I have this exact problem but can't seem to fix it...

This library supported React 16+ since December 2017. Just make sure you install the latest version on all react-leaflet dependencies.

**Comment by WapnerSensefarm** [comment]
> This library supported React 16+ since December 2017. Just make sure you install the latest version on all react-leaflet dependencies.

I see, thanks for clarifying :)
