### ISSUE TITLE
Unable to delete layers (shapes)

### ISSUE THREAD

**Issue by meitalweiss** [alex3165/react-leaflet-draw#8]
Hi, While trying to delete a layer, it seems like when clicking on the shape it doesn't recognize the layer and therefore unable to delete the layer from the map. 
I am able to edit the layers and save it. 

Any suggestion why this happens?

**Comment by alex3165** [comment]
Hi @meitalweiss sorry i haven't seen your issue before, is it still happening with the new release 0.10.1 ?
If so can you provide a jsfiddle or a link to a project with the issue ?
