### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by srghma** [alex3165/react-leaflet-draw#86]
from https://github.com/alex3165/react-leaflet-draw/pull/83

@alex3165 could you publish to NPM OR give me access to srghma@gmail.com OR we can setup https://github.com/marketplace/actions/publish-to-npm, which publishes automatically when version differs

**Comment by henrymoews** [comment]
@srghma: Alternatively until this issue is solved, could you check in the dist folder into this repo? That way I could use the latest improvements without having them to compile.

**Comment by sinnrrr** [comment]
+, also merged pr with TS types, waiting for publishing on NPM to use in my TS projest

**Comment by srghma** [comment]
STUPID ME, sorry everyone, actually i DID have a rights to npm, published a v 0.19.5

https://www.npmjs.com/package/react-leaflet-draw

`npm install && npm publish`

**Comment by srghma** [comment]
@sinnrrr , what's your username in npm, I want to invite you

**Comment by srghma** [comment]
published 0.19.6 (probably 0.19.5 had the old code)
